Replace Queue With Subscription and Remove Routing Key
ONSdigital/ssdc-rm-exception-manager pull request #10
Opened 2021-08-17 13:11 UTC by LeoKHoward

# Motivation and Context
Since changing to pub/sub, terminology is out of date so queue needs to become subscription and reference to routingKey needs to be removed

# What has changed
Changed queue to subscription
Removed routingKey
Updated tests

# How to test?
Run maven clean install and check it all passes

# Links
https://trello.com/c/XPwwUY31

2021-08-17 13:12 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change exception manager to have more meaningful error fields (5)](https://trello.com/c/XPwwUY31/2662-change-exception-manager-to-have-more-meaningful-error-fields-5)

2021-08-18 08:06 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/exceptionmanager/endpoint/ReportingEndpoint.java
> -    quarantinedMessage.setRoutingKey(skippedMessage.getRoutingKey());
shouldn't have removed `routingKey`... that will end up being renamed to `topic`

2021-08-18 08:06 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/exceptionmanager/model/dto/SkippedMessage.java
> -  private String routingKey;
shouldn't have removed `routingKey`... that will end up being renamed to `topic`

2021-08-18 08:06 UTC, NickGrantX commented on src/main/java/uk/gov/ons/ssdc/exceptionmanager/model/entity/QuarantinedMessage.java
> -  @Column private String routingKey;
shouldn't have removed `routingKey`... that will end up being renamed to `topic`

2021-08-18 08:07 UTC, NickGrantONS requested changes
See comments

2021-08-19 13:34 UTC, ryangrundy7 approved these changes

2021-08-19 15:42 UTC, NickGrantONS approved these changes

2021-08-23 10:10 UTC, merged